config/routes.rb
Rails.application.routes.draw do

  get 'users/finish_signup'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root 'posts#index'
  resources 'posts'
  resources 'categories'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :user
	has_many :post_categories
	has_many :categories, through: :post_categories


	validates :title, presence: true, length: {minimum: 6, maximum: 50}
	validates :description, presence: true, length: {minimum: 10}
end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_post, only: [:show, :edit, :destroy, :update]
  before_action only: [:edit, :update, :destroy] do
    owner @post
  end

  def index
    @posts = Post.all.includes(:categories)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_param)
    if @post.save
      flash[:notice] = 'Post Successfully Created'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_param)
      flash[:notice] = 'Post Successfully Updated'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def edit

  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post Successfully Deleted'
    redirect_to posts_path
  end


  private

  def get_post
    @post = Post.friendly.find(params[:id])
  end

  def post_param
    params.require(:post).permit(:title, :description, category_ids: [])
  end

end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

module PostsHelper
end

app/views/posts/_forms.html.erb
<%= render '_shared/error', obj: @post %>


<%= form_for @post do |t| %>
    <p>
      <span><%= t.label :title %></span><br>
      <%= t.text_field :title, autofocus: true %>
    </p>
    <p>
      <span><%= t.label :description %></span><br>
      <%= t.text_area :description, rows: 10, cols: 150, width: '100%' %>
    </p>
    <p>
      <strong><%= t.label 'Category' %></strong> :
      <%= t.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
          <%= b.check_box %><%= b.label %>
      <% end %>
    <p>
      <%= t.submit %>
    </p>
<% end %>


<%= link_to 'Back to Posts', posts_path %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'forms' %>

app/views/posts/index.html.erb
<h1><%= link_to 'All Posts', root_path %></h1>
<% if @posts.blank? %>
    <h1 align="center">Nothing in here !!</h1>
    <%= link_to 'Create New Post', new_post_path, style: 'text-align:center; margin:0px auto; display:inherit' %>
<% else %>
    <table>
      <thead>
      <tr>
        <th width="200px">Title</th>
        <th>Description</th>
        <th width="150px"></th>
      </tr>
      </thead>
      <tbody>
      <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td>
              <% if post.categories.any? %>
                  <table>
                    <tr>
                      <td><%= truncate(post.description, length: 150) %></td>
                    </tr>
                    <tr>
                      <td>
                        <small><strong>Categories :</strong></small>
                        <% post.categories.each do |c| %>
                            <small><em><%= link_to c.name, category_path(c), class: 'category' %></em></small>
                            |
                        <% end %></td>
                    </tr>
                  </table>
              <% else %>
                  <%= truncate(post.description, length: 150) %>
              <% end %>
            </td>
            <td><%= link_to 'Show', post_path(post) %> | <%= link_to 'edit', edit_post_path(post) %>
              | <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are you sure?"} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

	
	

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'forms' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>
<% if @post.categories.any? %>
    <ul>
      <% @post.categories.each do |category| %>
          <li><%= link_to category.name, category_path(category), class: 'category' %> </li>
      <% end %></ul>
<% end %>

<%= link_to 'Back to Posts', posts_path %>