config/routes.rb
Rails.application.routes.draw do

  get 'users/finish_signup'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root 'posts#index'
  resources 'posts'
  resources 'categories'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :post_categories
  has_many :posts, through: :post_categories


  validates :name, presence: true, length: {minimum: 3}
end

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_category, only: [:edit, :show, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(set_params)
    if @category.save
      flash[:success] = 'Category Successfully Created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(set_params)
      flash[:success] = 'Category Successfully Updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category Successfully Deleted'
    redirect_to categories_path
  end


  private

  def get_category
    @category = Category.friendly.find(params[:id])
  end

  def set_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_form.html.erb
<%= render '_shared/error', obj: @category %>



<%= form_for @category do |t| %>
    <p>
      <span><%= t.label :name %></span><br>
      <%= t.text_field :name, autofocus: true %>
    </p>
    <p>
      <%= t.submit %>
    </p>
<% end %>


<%= link_to 'Back', :back %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% if @categories.any? %>
    <ul class="category_page">
      <% @categories.each do |category| %>
          <li><%= link_to category.name, category_path(category), class: 'category' %>
            <span>[ <%= link_to 'Edit', edit_category_path(category) %>
              | <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"} %>
              ]</span></li>
      <% end %>
    </ul>
    <%= link_to 'Create New Category', new_category_path %>
<% else %>
    <p>No Categories here</p>
    <%= link_to 'Create New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Post related to - <%= @category.name %></h1>

<% if @category.posts.any? %>
    <table>
      <thead>
      <tr>
        <th width="150px">Title</th>
        <th>Content</th>
      </tr>
      </thead>
      <tbody>
      <% @category.posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.description %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <hr>
    <%= link_to 'Back', :back %>
<% else %>
    <p>No Post found here</p>
    <%= link_to 'Create New Post', new_post_path %> | <%= link_to 'Back', :back %>
<% end %>