config/routes.rb
Rails.application.routes.draw do

  get 'users/finish_signup'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  root 'posts#index'
  resources 'posts'
  resources 'categories'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<span class="common_nav">
  <%= link_to 'Home', root_path %>
  | <%= link_to 'New Post', new_post_path %>
  | <%= link_to 'Categories', categories_path %>
  | <%= link_to 'New Category', new_category_path %>
  <br>
</span>
<spna class="sign_inOut">
  <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      | <%= link_to 'Sign up', new_user_registration_path %>
      | <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      | <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
      | <%= link_to "Sign in with Dribbble", user_omniauth_authorize_path(:dribbble) %>
      | <%= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %>
  <% end %>
</spna>
<hr>
<br>

<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>
<%= yield %>
</body>
</html>